services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src
      - /src/LibRaw/object
    command: ["node", "/src/scripts/build.mjs"]
  bindgen:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/src
    command: [
      "npx",
      "-p", "@typed-cstruct/generator@0.5.0",
      "tcgen",
      "-h", "/src/LibRaw/libraw/libraw.h",
      "--clang-args=\"--sysroot=/emsdk/upstream/emscripten/cache/wasm/sysroot\"",
      "--entry-types=libraw_data_t",
      "--entry-types=libraw_processed_image_t",
      "/src/src/libraw-types.ts"]
