name: Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: ./.github/actions/setup
        id: setup
      - run: pnpm build
        env:
          SYSROOT: ${{ steps.setup.outputs.emscripten }}/cache/sysroot
      - run: pnpm check
      - run: pnpm test
